version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  commit-message:
    prefix: "[Dependency] "
    prefix-development: "[DevDependency] "
