events {}
http {
    server {
        listen 80;
        server_name localhost;

        sub_filter '0.0.0.0:4000' 'localhost:4000';
        sub_filter '0.0.0.0:35729' 'localhost:35729';
        sub_filter_once off;
        sub_filter_types text/html application/json;

        location / {
            proxy_pass http://docs:4000;
            proxy_set_header Host $host;
        }

        location /livereload {
            proxy_pass http://docs:35729;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
