name: 'Submitty PR Title Check'
on:
  pull_request:
    # check when PR
    # * is created,
    # * title is edited, and
    # * new commits are added (to ensure failing title blocks merging)
    types: [ opened, reopened, edited, synchronize ]

jobs:
  title-check:
    runs-on: ubuntu-latest
    steps:
      #
      # pull request titles format rules here:
      # https://submitty.org/developer/getting_started/make_a_pull_request
      #
      # [<TYPE>:<MODULE>] <SUBJECT>
      #
      - uses: submitty/action-pr-title@main
