name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Ruby version
      id: rubyversion
      run: echo "::set-output name=version::$(curl https://raw.githubusercontent.com/github/pages-gem/master/.ruby-version)"

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ steps.rubyversion.outputs.version }}
        bundler-cache: true

    - name: Install dependencies
      run: bundle install

    - name: Build Site
      run: bundle exec jekyll build

    - name: Check Links
      run: bundle exec htmlproofer ./_site --assume-extension  --alt-ignore '/.*/' --disable_external
